# Generated by Django 3.1.6 on 2024-01-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='qtd_total',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
